
export enum SHIPMENTS {
  GET_ALL_SHIPMENTS = 'INITIATE_CANVAS',
  GET_ALL_SHIPMENTS_DATA = 'INITIATE_CANVAS_DATA',
  GET_ALL_SHIPMENTS_DATA_ERROR = 'INITIATE_CANVAS_DATA_ERROR',
  REMOVE_SHIPMENT = 'REMOVE_SHIPMENT',
}

export enum LOGIN {
  USER_LOGIN= `USER_LOGIN`,
  LOGIN_LOADING= `LOGIN_LOADING`,
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE"
}

export enum LOGIN_SUCCESS {
  LOGIN_SUCCESS= `LOGIN_SUCCESS`
}

export enum LOGIN_FAILURE {
  LOGIN_FAILURE= `LOGIN_FAILURE`
}