
export enum SHIPMENTS {
  GET_ALL_SHIPMENTS = 'INITIATE_CANVAS',
  GET_ALL_SHIPMENTS_DATA = 'INITIATE_CANVAS_DATA',
  GET_ALL_SHIPMENTS_DATA_ERROR = 'INITIATE_CANVAS_DATA_ERROR',
  REMOVE_SHIPMENT = 'REMOVE_SHIPMENT',
}



export enum MBL_SHIPMENTS {
  GET_ALL_MBL_SHIPMENTS = 'INITIATE_MBL',
  GET_ALL_MBL_SHIPMENTS_DATA = 'INITIATE_MBL_CANVAS_DATA',
  GET_ALL_MBL_SHIPMENTS_DATA_ERROR = 'INITIATE_MBL_CANVAS_DATA_ERROR',
  REMOVE_MBL_SHIPMENT = 'REMOVE_MBL_SHIPMENT',
  SAVE_HBL_SHIPMENT = 'SAVE_HBL_SHIPMENT'

}

export enum HBL_SHIPMENTS {
  GET_ALL_HBL_SHIPMENTS = 'INITIATE_HBL',
  GET_ALL_HBL_SHIPMENTS_DATA = 'INITIATE_HBL_CANVAS_DATA',
  GET_ALL_HBL_SHIPMENTS_DATA_ERROR = 'INITIATE_HBL_CANVAS_DATA_ERROR',
  REMOVE_HBL_SHIPMENT = 'REMOVE_HBL_SHIPMENT',


}
export enum LOGIN {
  USER_LOGIN= `USER_LOGIN`,
  LOGIN_LOADING= `LOGIN_LOADING`,
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE"
}

export enum LOGIN_SUCCESS {
  LOGIN_SUCCESS= `LOGIN_SUCCESS`
}

export enum LOGIN_FAILURE {
  LOGIN_FAILURE= `LOGIN_FAILURE`
}
